//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP1Change.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_tr1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_tr1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CP1Change.Resources.Resource.tr1", typeof(Resource_tr1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplamaya Başla.
        /// </summary>
        public static string MPCAL {
            get {
                return ResourceManager.GetString("MPCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzemeyi Seçiniz.
        /// </summary>
        public static string MPMS {
            get {
                return ResourceManager.GetString("MPMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz....
        /// </summary>
        public static string MPW {
            get {
                return ResourceManager.GetString("MPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boyut. Tolerans.
        /// </summary>
        public static string PG1DT {
            get {
                return ResourceManager.GetString("PG1DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Kalınlık&amp;#x0a;-En.
        /// </summary>
        public static string PG1DTB {
            get {
                return ResourceManager.GetString("PG1DTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Metrajı-1.
        /// </summary>
        public static string PG1FL1 {
            get {
                return ResourceManager.GetString("PG1FL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -F.In.Dia&amp;#x0a;-F.Out.Dia&amp;#x0a;-F.Thickness.
        /// </summary>
        public static string PG1FL1B {
            get {
                return ResourceManager.GetString("PG1FL1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Metrajı-2.
        /// </summary>
        public static string PG1FL2 {
            get {
                return ResourceManager.GetString("PG1FL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -F.Miktar&amp;#x0a;-F.Kalınlık&amp;#x0a;-F.En.
        /// </summary>
        public static string PG1FL2B {
            get {
                return ResourceManager.GetString("PG1FL2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Ağırlığı-1.
        /// </summary>
        public static string PG1FW1 {
            get {
                return ResourceManager.GetString("PG1FW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -F.İç Çap&amp;#x0a;-F.Dış Çap&amp;#x0a;-F.Kalınlık.
        /// </summary>
        public static string PG1FW1B {
            get {
                return ResourceManager.GetString("PG1FW1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Ağırlığı-2.
        /// </summary>
        public static string PG1FW2 {
            get {
                return ResourceManager.GetString("PG1FW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -F.Metraj&amp;#x0a;-F.Kalınlık&amp;#x0a;-F.En.
        /// </summary>
        public static string PG1FW2B {
            get {
                return ResourceManager.GetString("PG1FW2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İç Çap Hesabı-1.
        /// </summary>
        public static string PG1ID1 {
            get {
                return ResourceManager.GetString("PG1ID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Miktar&amp;#x0a;-Dış Çap&amp;#x0a;-En.
        /// </summary>
        public static string PG1ID1B {
            get {
                return ResourceManager.GetString("PG1ID1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İç Çap Hesabı-1.
        /// </summary>
        public static string PG1ID2 {
            get {
                return ResourceManager.GetString("PG1ID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Metraj&amp;#x0a;-Dış Çap&amp;#x0a;-Kalınlık.
        /// </summary>
        public static string PG1ID2B {
            get {
                return ResourceManager.GetString("PG1ID2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I-Unit Hesabı.
        /// </summary>
        public static string PG1IU {
            get {
                return ResourceManager.GetString("PG1IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Dalga Boyu&amp;#x0a;-Dalga Yüksek.
        /// </summary>
        public static string PG1IUB {
            get {
                return ResourceManager.GetString("PG1IUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metraj Hesabı-1.
        /// </summary>
        public static string PG1L1 {
            get {
                return ResourceManager.GetString("PG1L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -İç Çap&amp;#x0a;-Dış Çap&amp;#x0a;-Kalınlık.
        /// </summary>
        public static string PG1L1B {
            get {
                return ResourceManager.GetString("PG1L1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metraj Hesabı-2.
        /// </summary>
        public static string PG1L2 {
            get {
                return ResourceManager.GetString("PG1L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Miktar&amp;#x0a;-En&amp;#x0a;-Kalınlık.
        /// </summary>
        public static string PG1L2B {
            get {
                return ResourceManager.GetString("PG1L2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mek. Özellikler.
        /// </summary>
        public static string PG1MP {
            get {
                return ResourceManager.GetString("PG1MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Alaşım&amp;#x0a;-Kondüsyon&amp;#x0a;-Kalınlık.
        /// </summary>
        public static string PG1MPB {
            get {
                return ResourceManager.GetString("PG1MPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dış Çap Hesabı-1.
        /// </summary>
        public static string PG1OD1 {
            get {
                return ResourceManager.GetString("PG1OD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -İç Çap&amp;#x0a;-En&amp;#x0a;-Miktar.
        /// </summary>
        public static string PG1OD1B {
            get {
                return ResourceManager.GetString("PG1OD1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dış Çap Hesabı-2.
        /// </summary>
        public static string PG1OD2 {
            get {
                return ResourceManager.GetString("PG1OD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -İç Çap&amp;#x0a;-Metraj&amp;#x0a;-Kalınlık.
        /// </summary>
        public static string PG1OD2B {
            get {
                return ResourceManager.GetString("PG1OD2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boya  Hesabı-1.
        /// </summary>
        public static string PG1P1 {
            get {
                return ResourceManager.GetString("PG1P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Miktar&amp;#x0a;-Kalınlık&amp;#x0a;-Boya Kal&amp;#x0a;-Kaplama.
        /// </summary>
        public static string PG1P1B {
            get {
                return ResourceManager.GetString("PG1P1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boya  Hesabı-2.
        /// </summary>
        public static string PG1P2 {
            get {
                return ResourceManager.GetString("PG1P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Miktar&amp;#x0a;-Boya Cins&amp;#x0a;-Kalınlık&amp;#x0a;-Boya Kal.
        /// </summary>
        public static string PG1P2B {
            get {
                return ResourceManager.GetString("PG1P2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalınlık Hesabı-1.
        /// </summary>
        public static string PG1T1 {
            get {
                return ResourceManager.GetString("PG1T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Miktar&amp;#x0a;-Metraj&amp;#x0a;-En.
        /// </summary>
        public static string PG1T1B {
            get {
                return ResourceManager.GetString("PG1T1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalınlık Hesabı-2.
        /// </summary>
        public static string PG1T2 {
            get {
                return ResourceManager.GetString("PG1T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -İç Çap&amp;#x0a;-Dış Çap&amp;#x0a;-Metraj.
        /// </summary>
        public static string PG1T2B {
            get {
                return ResourceManager.GetString("PG1T2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar Hesabı-1.
        /// </summary>
        public static string PG1W1 {
            get {
                return ResourceManager.GetString("PG1W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Metraj&amp;#x0a;-En&amp;#x0a;-Kalınlık.
        /// </summary>
        public static string PG1W1B {
            get {
                return ResourceManager.GetString("PG1W1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar Hesabı-2.
        /// </summary>
        public static string PG1W2 {
            get {
                return ResourceManager.GetString("PG1W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -İç Çap&amp;#x0a;-Dış Çap&amp;#x0a;-En.
        /// </summary>
        public static string PG1W2B {
            get {
                return ResourceManager.GetString("PG1W2B", resourceCulture);
            }
        }
    }
}
