//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CP1.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Calculate.
        /// </summary>
        public static string MPCAL {
            get {
                return ResourceManager.GetString("MPCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Material.
        /// </summary>
        public static string MPMS {
            get {
                return ResourceManager.GetString("MPMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome....
        /// </summary>
        public static string MPW {
            get {
                return ResourceManager.GetString("MPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamen. Tol..
        /// </summary>
        public static string PG1DT {
            get {
                return ResourceManager.GetString("PG1DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Thickness&amp;#x0a;-Width.
        /// </summary>
        public static string PG1DTB {
            get {
                return ResourceManager.GetString("PG1DTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Lenght Calc-1.
        /// </summary>
        public static string PG1FL1 {
            get {
                return ResourceManager.GetString("PG1FL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -F.In.Dia&amp;#x0a;-F.Out.Dia&amp;#x0a;-F.Thickness.
        /// </summary>
        public static string PG1FL1B {
            get {
                return ResourceManager.GetString("PG1FL1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Lenght Calc-2.
        /// </summary>
        public static string PG1FL2 {
            get {
                return ResourceManager.GetString("PG1FL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -F.Weight&amp;#x0a;-F.Thick&amp;#x0a;-F.Width.
        /// </summary>
        public static string PG1FL2B {
            get {
                return ResourceManager.GetString("PG1FL2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Weight Calc-1.
        /// </summary>
        public static string PG1FW1 {
            get {
                return ResourceManager.GetString("PG1FW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -F.In.Dia&amp;#x0a;-F.Out.Dia&amp;#x0a;-F.Thickness.
        /// </summary>
        public static string PG1FW1B {
            get {
                return ResourceManager.GetString("PG1FW1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Weight Calc-2.
        /// </summary>
        public static string PG1FW2 {
            get {
                return ResourceManager.GetString("PG1FW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -F.Length&amp;#x0a;-F.Thick&amp;#x0a;-F.Width.
        /// </summary>
        public static string PG1FW2B {
            get {
                return ResourceManager.GetString("PG1FW2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Dia Calc-1.
        /// </summary>
        public static string PG1ID1 {
            get {
                return ResourceManager.GetString("PG1ID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Weight&amp;#x0a;-Out.Dia&amp;#x0a;-Width.
        /// </summary>
        public static string PG1ID1B {
            get {
                return ResourceManager.GetString("PG1ID1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Dia Calc-2.
        /// </summary>
        public static string PG1ID2 {
            get {
                return ResourceManager.GetString("PG1ID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Length&amp;#x0a;-Out.Dia&amp;#x0a;-Thickness.
        /// </summary>
        public static string PG1ID2B {
            get {
                return ResourceManager.GetString("PG1ID2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I-Unit Calc.
        /// </summary>
        public static string PG1IU {
            get {
                return ResourceManager.GetString("PG1IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I-Unit Calc.
        /// </summary>
        public static string PG1IUB {
            get {
                return ResourceManager.GetString("PG1IUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Calc-1.
        /// </summary>
        public static string PG1L1 {
            get {
                return ResourceManager.GetString("PG1L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -In.Dia&amp;#x0a;-Out.Dia&amp;#x0a;-Thickness.
        /// </summary>
        public static string PG1L1B {
            get {
                return ResourceManager.GetString("PG1L1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Calc-2.
        /// </summary>
        public static string PG1L2 {
            get {
                return ResourceManager.GetString("PG1L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Weight&amp;#x0a;-Width&amp;#x0a;-Thickness.
        /// </summary>
        public static string PG1L2B {
            get {
                return ResourceManager.GetString("PG1L2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mech. Prop.
        /// </summary>
        public static string PG1MP {
            get {
                return ResourceManager.GetString("PG1MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Alloy&amp;#x0a;-Temper&amp;#x0a;-Thickness.
        /// </summary>
        public static string PG1MPB {
            get {
                return ResourceManager.GetString("PG1MPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Dia Calc-1.
        /// </summary>
        public static string PG1OD1 {
            get {
                return ResourceManager.GetString("PG1OD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -In.Dia&amp;#x0a;-Width&amp;#x0a;-Weight.
        /// </summary>
        public static string PG1OD1B {
            get {
                return ResourceManager.GetString("PG1OD1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Dia Calc-2.
        /// </summary>
        public static string PG1OD2 {
            get {
                return ResourceManager.GetString("PG1OD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -In.Dia&amp;#x0a;-Length&amp;#x0a;-Thickness.
        /// </summary>
        public static string PG1OD2B {
            get {
                return ResourceManager.GetString("PG1OD2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Calc-1.
        /// </summary>
        public static string PG1P1 {
            get {
                return ResourceManager.GetString("PG1P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Weight&amp;#x0a;-Thickness&amp;#x0a;-Paint Thick.&amp;#x0a;-Coverage.
        /// </summary>
        public static string PG1P1B {
            get {
                return ResourceManager.GetString("PG1P1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Calc-2.
        /// </summary>
        public static string PG1P2 {
            get {
                return ResourceManager.GetString("PG1P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Weight&amp;#x0a;-Paint Type&amp;#x0a;-Mat.Thick.&amp;#x0a;-Paint Thick..
        /// </summary>
        public static string PG1P2B {
            get {
                return ResourceManager.GetString("PG1P2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness Calc-1.
        /// </summary>
        public static string PG1T1 {
            get {
                return ResourceManager.GetString("PG1T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Weight&amp;#x0a;-Length&amp;#x0a;-Width.
        /// </summary>
        public static string PG1T1B {
            get {
                return ResourceManager.GetString("PG1T1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness Calc-2.
        /// </summary>
        public static string PG1T2 {
            get {
                return ResourceManager.GetString("PG1T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -In.Dia&amp;#x0a;-Out.Dia&amp;#x0a;-Length.
        /// </summary>
        public static string PG1T2B {
            get {
                return ResourceManager.GetString("PG1T2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Calc-1.
        /// </summary>
        public static string PG1W1 {
            get {
                return ResourceManager.GetString("PG1W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Length&amp;#x0a;-Width&amp;#x0a;-Thickness.
        /// </summary>
        public static string PG1W1B {
            get {
                return ResourceManager.GetString("PG1W1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Calc-2.
        /// </summary>
        public static string PG1W2 {
            get {
                return ResourceManager.GetString("PG1W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -In.Dia&amp;#x0a;-Out.Dia&amp;#x0a;-Width.
        /// </summary>
        public static string PG1W2B {
            get {
                return ResourceManager.GetString("PG1W2B", resourceCulture);
            }
        }
    }
}
